
const rumorData = {
  any: [
    "someone claims a dragon was spotted circling the old watchtower at sunset",
    "candles flicker ominously in the abandoned chapel, even at noon",
    "a traveling bard disappeared without a trace, leaving behind only a single shoe",
    "the local catacombs echo with ghostly laughter at night",
    "an old woman swears she saw a giant boar vanish into thin air",
    "a spectral caravan was seen rolling through the main street at midnight",
    "children whisper about a monster that lives in the well outside town",
    "the mayor's cat cackles like a hyena when no one else is around",
    "a beggar found a key made of solid gold, but none know what it opens",
    "strange lights appear atop the nearby hill at dusk",
    "a cloaked figure sells potions that make people forget entire days",
    "the blacksmith's forge glows a faint green when the moon is full",
    "someone found a massive footprint near the river, too large for any known beast",
    "the old mill wheel sometimes spins backwards at dawn",
    "haunting music drifts through the streets, but no source can be found",
    "the farmland to the west suffers from unexplained crop circles",
    "a fisherman claims to have caught a fish that spoke a warning of doom",
    "the library's books rearrange themselves each morning",
    "merchants heading north vanish, and their goods end up in the bazaar days later",
    "a giant raven perched on the city wall for hours, staring silently",
    "the butcher's shop has been closed for weeks, but at night, lights can be seen inside",
    "a traveling jester performed a tune that put half the tavern to sleep instantly",
    "the graveyard caretaker swears the statues change position each night",
    "an eerie howling can be heard from the clock tower at midday",
    "someone found a torn diary page describing a hidden crypt beneath the city",
    "a mysterious figure was spotted floating above the river at twilight",
    "the oldest oak in the forest bled red sap when cut",
    "a local merchant's reflection in the mirror is slightly delayed",
    "people claim a pack of ghostly hounds prowls the outskirts at dusk",
    "the innkeeper found footprints on the ceiling of the cellar",
    "a horse-drawn carriage rides through the streets with no driver in sight",
    "glowing mushrooms grow overnight in random doorsteps around town",
    "the stone gargoyles on the castle parapet have been smiling lately",
    "farmers hear whispers among the cornstalks late at night",
    "the blacksmith hammered a blade that hums a lullaby in the moonlight",
    "a wandering pilgrim collapsed, muttering cryptic warnings of a blood moon",
    "an ancient mosaic was uncovered, depicting the town's destruction",
    "someone found a map detailing a labyrinth beneath the fortress",
    "the tailor's mannequins were seen dancing through the shop window at midnight",
    "the local tavern serves an ale that causes patrons to speak in rhyme for hours",
    "a scholar in the library claims a hidden door leads to an endless corridor",
    "cattle have been found with strange symbols carved into their hides",
    "the reflection in the city fountain sometimes shows a different skyline",
    "a child was found wandering alone in the forest, claiming to have played with fairies",
    "the war memorial statue wept real tears last full moon",
    "a traveling merchant sold a coin that screams when dropped",
    "the black cat crossing the mayor's path turned white halfway across the road",
    "a local painter vanished, leaving behind a half-finished portrait of an alien city",
    "someone opened a locked chest in the attic and found it empty except for a beating heart",
    "the abandoned mines are said to echo with the voices of those long dead",
    "a fisherman reeled in a severed hand wearing an ornate signet ring",
    "the inn's sign keeps rearranging its letters to form cryptic messages",
    "a pack of wild dogs roams the outskirts, but they vanish at sunrise",
    "the orchard's apples are all black inside this season",
    "the windmill on the cliff sometimes runs without wind, at midnight precisely",
    "a phantom fiddler was heard playing on the rooftops during a thunderstorm",
    "the old stone bridge collapsed years ago, yet some see it intact at night",
    "the clock tower rings thirteen times on certain nights",
    "a heavy book in the chapel re-writes its own pages with prophecies of doom",
    "the blacksmith's shadow forges imaginary weapons on its own",
    "an herbalist claims to have found a flower that speaks riddles",
    "footsteps can be heard on cobblestone roads even when they’re empty",
    "the wizard's apprentice keeps babbling about an impending apocalypse",
    "local hunters found a deer with glowing green eyes that vanished into thin air",
    "the old fortress torches light themselves after sunset, despite being abandoned",
    "a phantom ball of light was seen dancing over the pond at midnight",
    "someone discovered a dagger that leaves no reflection in mirrors",
    "the local orphanage staff claim a presence tucks the children in at night",
    "the statue of a famous hero turned to face the wrong direction last week",
    "a soldier returned from a distant war, but nobody recognizes his uniform or language",
    "the chandelier in the mayor's hall sometimes drips molten wax in the shape of runes",
    "all the ravens in town gather on the same rooftop each morning for an hour",
    "an underground passage was found behind a crumbling tombstone, leading who knows where",
    "a blacksmith’s horse turned to solid stone mid-gallop",
    "strange graffiti appears on walls, each depicting an eye with a slash through it",
    "the flower shop keeps receiving bouquets ordered by a ghostly name",
    "tall, robed silhouettes have been glimpsed on rooftops at dawn",
    "the royal crest above the palace gate flickers as if it's made of illusion",
    "a traveling merchant sold a jar that laughs when opened",
    "a second moon was seen in the sky last month, then vanished the next night",
    "people claim a monstrous figure lurks in the reflection of the fountain but not above it",
    "the church bell rings of its own accord whenever a child is born in the city",
    "night watchmen keep encountering a lost child who disappears upon approach",
    "someone found a small door in a cellar that leads to a room bigger than the house",
    "a hidden message was found carved into the underside of every bench in the town square",
    "the mayor's dog barks at an invisible presence outside the bedroom window nightly",
    "visitors to the old library keep forgetting why they came once they step inside",
    "wolves in the forest have begun howling at noon instead of midnight",
    "the miller discovered footprints on the ceiling of the mill's interior",
    "an ancient shield was found under the city gate, etched with the face of a weeping goddess",
    "harvesters found gold coins in the wheat fields, no one knows who placed them",
    "glowing orbs circle the old gallows hill whenever someone attempts to cut it down",
    "a dwarven prospector claims there's a hidden vault under the tavern floor",
    "the hush that falls over the city at midday is unnatural, as if time stands still",
    "a local noble was seen haggling with a skeleton in the graveyard at dusk",
    "the blacksmith's anvil has started ringing like a bell on its own each sunrise",
    "a woman claims she woke up outside the city walls with no recollection of the past week"
  ],

  political: [
    "the baron is rumored to be bankrupt, secretly selling heirlooms to maintain appearances",
    "the new tax collector pockets extra coin from unsuspecting townsfolk",
    "rumor has it two noble families plan to merge via an arranged marriage for political power",
    "the lord’s steward is forging the lord’s seal on secret documents",
    "a group of disgruntled farmers formed a militia to protest rising taxes",
    "the queen’s advisors bicker openly, suggesting a power struggle in the court",
    "the mayor has a hidden slush fund for bribing important merchants",
    "a diplomat from a rival kingdom arrived unannounced, stirring fears of espionage",
    "town guards have been turning a blind eye to certain smuggling operations",
    "the duke’s heir was found meeting with a rebellious group at night",
    "tensions between the city watch and the mercenary guild have escalated to street fights",
    "a high-ranking official was overheard making a deal with shady underworld figures",
    "the local bishop is rumored to have old ties to a banned cult",
    "the royal treasury is suspiciously low, prompting talk of new taxes or forced donations",
    "the captain of the guard is in love with the enemy general’s daughter, risking security",
    "the spymaster has gone missing, leaving behind cryptic notes about a coup",
    "an assassin’s guild claims the baron hasn’t paid for a previous favor",
    "the city council can’t agree on the new trade route, stalling critical goods",
    "a popular merchant was seen entering the palace with a locked chest at midnight",
    "the princess secretly organizes midnight rallies to address the people’s woes",
    "a group of knights loyal to the crown suspect a viceroy of treason",
    "the local judge has been reversing convictions for a price",
    "the high general’s medals might be for battles that never happened",
    "city officials vanish after investigating the fortress in the mountains",
    "a senator pockets bribes from foreign envoys, fueling rampant corruption",
    "the treasury ledger doesn’t match the official budget, funds are missing",
    "some suspect the royal family is truly half-doppelganger, replaced over generations",
    "rebels gather under the old oak tree at dusk to plan an uprising",
    "the baron’s advisor demands an inventory of all local blacksmiths, preparing for war",
    "the tavern rumors claim an influential merchant lords over half the city’s rackets",
    "the queen’s cousin was denied entry to the court, stoking rumors of hidden scandals",
    "the tax on adventurers’ loot doubled overnight, causing uproar among the guilds",
    "a foreign prince claims ancestral rights to the region, threatening to lay siege",
    "the city watch found coded letters implicating a noble family in a slave trade",
    "a suspicious shipment arrives monthly at the palace gates, no one knows what’s inside",
    "the chamberlain was seen sneaking out of the dungeons with parchments at dawn",
    "an old prophecy states that a child of two noble houses will dethrone the current king",
    "the war minister is rumored to be selling arms to the enemy kingdom",
    "the regent’s new laws heavily favor certain guilds while bankrupting smaller trades",
    "the archduke’s personal guard are rumored to be cultists in disguise",
    "factions within the city council propose seceding from the kingdom entirely",
    "the local baroness hires mercenaries to quell peasant revolts in the farmland",
    "an exiled noble returned with a letter of pardon, but no one knows who signed it",
    "the king’s spymaster blackmails half the court, ensuring loyalty through fear",
    "a traveling bard found secret decrees that show the queen plans to disband the city guard",
    "the city’s champion swordsman might have cheated in the annual tournament, sparking fury",
    "the local judge is a puppet, receiving orders from a hidden puppetmaster deep in the city",
    "messengers from a distant empire arrived, offering a suspicious alliance",
    "the official scribe keeps forging the mayor’s signature to rezone districts for profit",
    "the new earl actually belongs to a line of pirates from the southern seas",
    "the castle steward has sold old castle artifacts under the table",
    "a pamphlet circulates accusing the princess of unholy practices to maintain beauty",
    "the noble family’s crest changed overnight, indicating a secret change in lineage",
    "the guard captain was bribed to release a notorious bandit lord, stirring panic",
    "someone discovered coded letters referencing a “great betrayal” set to occur soon",
    "the beloved queen is rumored to be a puppet for a reclusive mage in the tower",
    "council members are voting on a law requiring mages to register, stirring outrage",
    "the archbishop is secretly amassing an army of zealots to overthrow the monarchy",
    "town criers are censored to only spread good news about a failing harvest",
    "a traveling soothsayer predicted the mayor’s downfall within the week, fueling suspicion",
    "the new tax law heavily fines anyone wearing a hood, targeting certain subcultures",
    "the local guard discovered a plot to poison city officials but can’t identify the sponsor",
    "a disgraced noble begs for an audience with the king, claiming knowledge of a deep betrayal",
    "the old castle dungeons are rumored to hold political prisoners who have no trial",
    "someone found an edict that grants lands to an unknown heir rumored to be half-monster",
    "the knight-commander refuses to patrol certain neighborhoods, citing archaic feudal rights",
    "a secret council has formed, aiming to forcibly dethrone the region’s ruler",
    "the local militia demands higher pay or threatens to disband, leaving the city defenseless",
    "the annual tribute to the crown doubled this year, but no reason was given",
    "the city’s bailiff was caught distributing stolen goods to orphans, dividing public opinion",
    "a rumor says the next in line to the throne was fathered by a foreign warlord",
    "the count’s prized griffon cavalry was sold off discreetly to an unknown buyer",
    "the mayor’s staff has locked the mayor in their home, claiming they’re unfit to rule",
    "doctored battle reports hide the fact that the kingdom is losing a major war",
    "the baron’s daughter was spotted kissing a common blacksmith, scandalizing the court",
    "the spymaster’s secret network extends into every merchant stall and tavern corner",
    "someone found a hidden chamber beneath the castle stables containing forged documents",
    "the city gates have new guards with strange accents who answer to no local authority",
    "each morning, a letter from a rebel leader appears on the palace gates, mocking the king",
    "the bishop was overheard complaining the queen forced a new religious tax on the faithful",
    "an entire group of knights left the city, forming a rogue order opposed to the monarchy",
    "the earl next door prepares for war, citing an ancient border dispute that might be valid",
    "the annual “loyalty festival” ended abruptly after an attempt on the baron’s life",
    "the new steward bans gatherings after sundown, spurring conspiracies of a hush regime",
    "some claim the jester in the royal court is actually the king’s top advisor in disguise"
  ],

  supernatural: [
    "candles in the chapel sometimes bleed real blood",
    "a ghostly child wanders the alleys, asking for lost parents from centuries ago",
    "the moon was replaced by a gigantic eye for a full hour last week",
    "the statue in the cemetery turned to watch visitors pass by",
    "a child’s lullaby echoes from an abandoned house at twilight, though no children live there",
    "the reflection of a man in the river wore different clothes than he did",
    "a bright star fell into the western hills, but no crater or debris was found",
    "the old battlefield outside town sometimes re-enacts itself at dawn with ghostly soldiers",
    "a swirl of black feathers descends upon the church roof each time the priest prays",
    "people say the miller’s cat speaks in a human voice when it thinks it’s alone",
    "a wandering minstrel claims they saw a woman step out of a mirror and disappear",
    "the forest paths shift at night, leading travelers in circles until sunrise",
    "a merchant woke up with runic symbols etched into his skin that glow faintly at night",
    "the sun dimmed for ten minutes last week, no eclipse predicted",
    "faint chanting can be heard from a cave that was sealed centuries ago",
    "a farmer’s livestock keep giving birth to two-headed calves",
    "the ghost of a knight stands guard on the crumbling bridge, challenging passersby",
    "a local mage insists portals to other realms open randomly in the countryside",
    "all the candles in a dinner party burned blue, then the hostess vanished",
    "a swirl of autumn leaves blew through the market, forming a face that whispered a name",
    "someone saw a reflection in the well that wasn’t their own, beckoning them deeper",
    "a sinister red glow illuminates the forest canopy on certain nights",
    "the local midwife claims she delivered a baby with glowing eyes that laughed at birth",
    "the watchtower bell rings on its own, even though the rope was cut decades ago",
    "a child found a doll in the attic that cries real tears if left in the dark",
    "the blacksmith’s daughter claims to have seen her dead mother’s face in the forge embers",
    "a rainbow appeared in the sky at midnight, shimmering with eerie luminescence",
    "the statue of a long-deceased king whispered a prophecy to a guard passing by",
    "the old map in the library changes its layout each full moon, revealing hidden places",
    "someone tried to bury a loved one, but the grave kept refusing the corpse",
    "the local bar sells a drink called ‘Ghost’s Sigh,’ which sometimes speaks secrets aloud",
    "a traveler’s shadow parted ways with them at sunset, continuing north on its own",
    "the grand chandelier in the mansion shows shadows of dancing figures when unoccupied",
    "residents near the lake claim they see an underwater city if they stare long enough",
    "the catacombs occasionally exhale a gust of icy wind that sounds like a name",
    "flowers on certain graves never wilt, even out of season",
    "the orchard orchard-keeper’s eyes glow softly, and fruit trees bend to her will",
    "a crack in the city wall weeps a black liquid on nights of the new moon",
    "ghostly riders gallop across the horizon at sunrise, then vanish with the morning haze",
    "the church organ played itself at dawn, producing hauntingly discordant melodies",
    "someone found a door in their bedroom that leads to a forest glade miles away",
    "once a month, the city is blanketed in silent fog where no sound carries",
    "the mosaic floor in the temple rearranges to form cryptic messages in its tiles",
    "a traveling oracle claims the entire region is an illusion cast by a slumbering titan",
    "people near the old orchard keep hearing a lullaby that soothes them to sleep instantly",
    "the fortress walls bleed red dew at midday in the heat of summer",
    "the footprints of a child lead out of a locked crypt, continuing into the forest",
    "the reflection of the moon in the river shows two moons instead of one",
    "a fisherman claims he saw a giant eel with a human face in the depths of the lake",
    "the old scarecrow in the field vanished, replaced by a stone statue with outstretched arms",
    "an ancient clock with no gears or power source still chimes perfectly each hour",
    "a mirror in the inn’s hallway shows passersby as rotting corpses for a split second",
    "the crystal in the jeweler’s shop window pulses like a heartbeat at night",
    "the footprints around a murder scene lead in circles, as though the victim walked away after death"
  ],

  lighthearted: [
    "the local bard's lute broke, so he improvised with a frying pan—surprisingly popular",
    "a mischievous gnome swapped street signs, causing mild confusion for a day",
    "a dwarf started a 'beard grooming competition,' offering a barrel of ale as first prize",
    "someone claims the local goose honks on command if you pay it a copper coin",
    "the bakery introduced a cake so sweet that even pixies find it too sugary",
    "the stable boy discovered a horse that dances when played a lively tune",
    "a traveling circus arrived with a juggling minotaur act, stealing the town’s heart",
    "the tavern launched a ‘rowdiest laugh contest,’ awarding free drinks to winners",
    "children claim to have found a talking frog that tells terrible puns",
    "a halfling’s cooking class turned chaotic when the pot exploded into confetti",
    "the mayor’s wig flew off in the wind and got tangled on the statue in the main square",
    "someone replaced all the chairs in the guardhouse with squeaky stools",
    "a donkey has been spotted wearing a wizard’s hat, accompanied by a flute-playing kobold",
    "the blacksmith’s parrot learned to mimic the sound of a hammer striking an anvil, day and night",
    "a stray cat roams the tavern floors, meowing suspiciously like a drunkard after midnight",
    "the local wizard’s experiment temporarily turned his beard rainbow-colored",
    "a gnome claims he perfected a device that flips pancakes in mid-air flawlessly",
    "the annual pie-eating contest ended in a tie when two contestants fell asleep mid-bite",
    "someone replaced the city crier’s bell with a squeaky rubber mallet",
    "sheep in the meadow have started following a particularly charismatic goose",
    "the traveling merchant’s donkey stubbornly refuses to move unless bribed with carrots",
    "the baron tried to sing a love ballad to the baroness, only to cause a minor earthquake",
    "a local dwarf brags about out-drinking an ogre once, though no witnesses confirm",
    "someone discovered an enchanted pastry that hovers an inch above plates, nobody knows why",
    "the tavern’s newest drink glows pink under moonlight, tasting like cherries and regret",
    "a giddy sprite keeps sprinkling glitter over passersby, resulting in sparkling footprints",
    "there’s a rumor of a frog choir that appears only at dawn to sing lullabies",
    "an old wizard tried to cast a grand spell but succeeded only in creating tiny fireworks",
    "the city baker has a cunning raccoon assistant who measures out flour perfectly",
    "someone replaced the inn's sign with a large wooden duck wearing a crown",
    "the blacksmith accidentally forged a horseshoe with a face that smiles whenever it's heated",
    "children found a stray dog that can balance a spoon on its nose for treats",
    "the local bard’s new harp composition causes small flowers to bloom if played outdoors",
    "an eccentric tailor made a cloak of leaves that rustles to the rhythm of music",
    "a pig in the farm started learning door tricks from the farm dog, leading to open doors everywhere",
    "the duke tried to command a parade, but the parade followed a stray cat instead",
    "someone discovered a hidden orchard of fruit shaped like silly cartoon faces",
    "a jolly old dwarf built a tiny house for local pixies, and they pay rent in acorn caps",
    "the fishmonger’s parrot advertises fresh fish by squawking, ‘Fishy fish, don’t be squishy!’",
    "a guard challenged a halfling to a footrace but lost when tripped by the halfling’s pet ferret",
    "the local mage’s broom gained sentience and now complains about cleaning floors",
    "a group of traveling jesters staged an impromptu puppet show in the city square, mesmerizing crowds",
    "the wizard’s apprentice turned a cart horse into a miniature pony by mistake for a day",
    "someone found a pair of shoes that squeak random jokes whenever worn",
    "the orchard orchard-keeper plays lullabies on a flute that puts squirrels to sleep",
    "a gnome claims to have invented a device that polishes coins so well they glow in the dark",
    "the baron’s new personal chef only cooks foods shaped like smiley faces, delighting the staff",
    "an alchemist discovered a candy that changes your hair color for an hour after eating",
    "a wandering peddler sells ‘invisibility seeds’ that do nothing but taste like pumpkin seeds",
    "someone crocheted tiny sweaters for all the pigeons in the square, who wear them proudly",
    "the apprentice blacksmith forged a ‘clumsy sword’ that occasionally leaps out of its sheath",
    "a talking donkey has been teaching local children how to bray in perfect harmony"
  ],

  crime: [
    "a notorious jewel thief left a calling card shaped like a black rose at the scene",
    "the city watch discovered a hidden trapdoor in the bakery leading to smuggler tunnels",
    "a pickpocket ring trains street urchins to distract travelers with sob stories",
    "someone’s been sabotaging local farms by poisoning wells at night",
    "a rash of counterfeit coins hit the marketplace, minted with a missing queen’s face",
    "the local thieve’s guild offers a bounty on the guard captain’s prized sword",
    "a vigilante calling themselves ‘The Night Raven’ disrupts shady deals in back alleys",
    "the baron’s signet ring was stolen, forging false decrees around town",
    "a smuggler’s ship sank, but the captain insists someone sabotaged it from beneath the water",
    "a black-market auction of cursed relics is rumored to occur monthly in a hidden cellar",
    "the last three caravans to leave town never arrived at their destinations",
    "rumors say the undertaker sells corpses to necromancers after midnight",
    "the city’s banker absconded with half the vault, fleeing in the dead of night",
    "the mayor’s personal guard were found accepting bribes from a local crime lord",
    "someone’s been forging official travel papers for foreign agents",
    "the local fence claims to have acquired a dragon egg, inciting interest from shady buyers",
    "a stolen masterpiece painting reappeared in the noble’s gallery with a mocking note attached",
    "the region’s best lockpick left a carved signature in every victim’s front door",
    "a wave of break-ins only target libraries and archives—no valuables stolen except rare scrolls",
    "someone discovered a hidden tunnel under the jail, large enough for a cart to pass through",
    "a gang of masked bandits hold midnight horse races down the main street, terrorizing locals",
    "the new court jester is rumored to be an assassin working for a rival lord",
    "the old vault in the city hall stands wide open one morning, emptied without a trace",
    "a spree of missing pets points to illegal beast-fighting rings in the slums",
    "the blacksmith complains valuable ore shipments vanish between the mine and the forge",
    "the dreaded pirate queen hides among the town’s merchants, waiting for a signal",
    "a local forger crafts near-perfect fake paintings, some now hang in official halls",
    "footpads have been ambushing travelers on the old road, leaving them penniless but unharmed",
    "the thieves’ guild demands monthly tribute from shopkeepers, or ‘accidents’ happen",
    "a cunning burglar leaves riddles for the city watch, taunting them with each theft",
    "the city undertaker was caught hawking stolen family heirlooms from sealed coffins",
    "smoke bombs have caused chaos in the marketplace, covering small robberies under the haze",
    "the local wealthy merchant vanished, rumored to be blackmailed by a long-lost sibling",
    "someone found a crate of illicit potions labeled ‘Black Market Alchemy, handle carefully’",
    "the guard discovered a labyrinth of secret passages under the oldest inn, leading to stolen goods",
    "a ring of kidnappers targets well-off travelers, demanding strange ransoms in cryptic notes",
    "a wave of counterfeit potions claims to grant eternal youth but results in memory loss instead",
    "the black market deals in rare monster parts, fueling hunts for endangered creatures",
    "someone broke into the city armory, leaving behind footprints that abruptly vanish",
    "the watch captured a burglar with an enchanted bag full of valuables, but they can’t open it",
    "a shadowy figure in the tavern sells ‘incriminating documents’ to anyone with enough coin",
    "the signet ring of a deceased noble was spotted on a fence’s table, raising undead inheritance claims",
    "a spree of arsons plagues the wealthy district, leaving no clues behind",
    "the local watch believes a high-born official funds the largest thieves guild in the region",
    "the city’s top assassin works in broad daylight disguised as a juggler in the market square",
    "the new trade baron is rumored to be laundering stolen artifacts through legitimate shipments",
    "a con artist runs a shell game so convincing, even the city guard lost their week’s wages",
    "a small gang of halfling rogues is said to be unstoppable due to cunning illusions",
    "the price of rare spices soared after a series of warehouse fires—arson or sabotage?",
    "someone filched the palace treasury keys, though the guard insists they remain locked away",
    "a known bandit leader offers free ale at local taverns to recruit desperate townsfolk",
    "every night, loud crashing and cursing can be heard from the alchemist’s shop—no break-in found",
    "the city’s main gate was left open all night, and no guard was posted—suspicious negligence",
    "a legendary gem called ‘The Moon’s Tear’ was stolen from the museum, leaving a single white feather",
    "the new hire at the library is rumored to be systematically stealing rare tomes to resell",
    "a wave of pickpockets has the city guard swamped, but the thieves vanish into thin air",
    "the orchard orchard-keeper complains someone’s been cutting down trees for black market wood",
    "bloodstained coins keep appearing in merchant stalls, with no explanation of origin",
    "the city’s top gambler disappeared after winning big in a rigged card game",
    "a dwarven smuggler claims to run goods through an interplanar portal deep in the mines"
  ],

  mystery: [
    "the runes on the ancient monolith in the fields glow faintly at dusk, but no one can decipher them",
    "footprints lead into the haunted mansion but never come out, and no one who enters returns",
    "the reflection in the lake shows a grand castle where only ruins stand in reality",
    "a strange meteorite fell near the farmland, but it vanished overnight without a crater",
    "the blacksmith’s anvil has been humming a funeral dirge for days with no explanation",
    "someone found an ancient key hidden in a loaf of bread, but no lock for it has been found",
    "the orchard orchard-keeper harvests double-yield apples, yet all taste faintly of ash",
    "the miller’s youngest child speaks a language no one recognizes in her sleep",
    "an unmarked grave in the cemetery glows under moonlight, revealing fleeting symbols",
    "a ghost ship was spotted sailing on a landlocked lake, vanishing at dawn",
    "the church basement has a hidden door that no one can open, rumored sealed by a saint’s tears",
    "someone found a sealed letter addressed to a person who died centuries ago",
    "the old clock tower’s gears produce a new type of coin whenever it strikes midnight",
    "the apothecary’s cat can vanish into walls, reappearing hours later with new scratches",
    "a child found a ring in the woods that whispers their name whenever worn",
    "sparks of strange energy flicker in the air near the abandoned mine entrance",
    "the city guard captured a man who claimed to be from the future, bearing cryptic warnings",
    "the mountain peak glows with an eerie green light on the solstice, then fades",
    "a painting in the baron’s hall changes its background daily, as if traveling to new locations",
    "moths gather around one particular lamppost each night, forming patterns that resemble letters",
    "the lord’s prized horse turned into stone at sunrise, then back to flesh at sunset",
    "a forest glade once used for picnics now contains a single silver tree that sings at dawn",
    "the city’s labyrinth is rumored to shift every week, trapping explorers in new corridors",
    "a hole in the ground behind the temple leads to a chamber of crystals that hum with power",
    "the marketplace fountain’s water turned pitch black, but testing shows it’s normal water",
    "the night sky occasionally displays phantom constellations never recorded by astrologers",
    "someone discovered a bone flute in the catacombs that only plays on its own at midnight",
    "the castle gatehouse exudes a sweet smell whenever the moon is full",
    "a small statue outside the bakery moves slightly each day, as if traveling across town",
    "the venerable elder claims memories of being a dragon in a past life, describing hidden lairs in detail",
    "the scribe found a shelf of blank books in the library that write themselves when the moon is new",
    "a traveler claimed to see a double of himself wandering the roads, identical in every way",
    "the old orchard orchard-keeper found a door in a tree trunk leading to an underground library",
    "local dogs howled for three days straight, then all went silent at once, no cause found",
    "the ruins of an old tower reappeared overnight, though records say it was destroyed centuries ago",
    "someone discovered a puzzle box that hums when approached, but refuses to open for anyone",
    "the blacksmith’s forge erupted in blue flames, forging a blade with runes none can read",
    "a locked safe in the mayor’s office thumps from the inside like a heartbeat",
    "the wizard’s old lab glows from within, though it was sealed after the wizard vanished years ago",
    "the city’s water supply sometimes runs backward in the pipes, flooding random basements",
    "lone travelers on the main road hear disembodied singing about an ancient legend",
    "the orchard orchard-keeper’s footprints vanish a few steps behind him, as if erased by unseen hands",
    "an abandoned cabin in the woods has a chimney that smokes at midnight, though no one lives there",
    "the chapel’s bell tower harbors a nest of ravens that fly off in perfect geometric formations",
    "a farmer discovered footprints belonging to a giant chicken, measuring three feet per step",
    "the grave of a saint exudes a faint glow, but official church records deny the saint ever existed",
    "a floating orb of pale light drifts through the noble district, never deviating from its path",
    "the local bard overheard voices in an empty room, discussing an upcoming sacrifice",
    "during a recent thunderstorm, lightning struck the same tree seven times, leaving it unscathed",
    "the blacksmith claims their hammer sometimes tells them how to shape metal into perfect forms",
    "a lost hamlet is marked on old maps but can’t be found, though travelers occasionally stumble across it",
    "a sealed letter found in the archives details the city’s entire future, accurate up to the present day",
    "the revered statue in the plaza rotates at dawn to face the sun, yet it’s made of solid marble",
    "someone claims they found a hidden floor under the tavern’s basement containing archaic machines",
    "the temple’s holy water glows with starlight, even in total darkness",
    "a traveler spotted a crystal spire on the horizon, but no one else can see it or find it",
    "the nightly fog forms shapes of unknown creatures prowling through the streets",
    "farmers swear a giant crow watches them harvest, perched on a scarecrow that was never placed there",
    "the blacksmith’s apprentice found a note in the forge ashes that read ‘I am coming soon’",
    "the tailor’s shop mannequins rearrange themselves in elaborate scenes after closing hours",
    "rumor says the guardian gargoyle on the old tower left its perch to roam the countryside",
    "an empty boat drifted into the harbor with a single word carved inside: ‘Remember’",
    "the city’s official records show a blank page for the entire year 200 years ago, no explanation",
    "footsteps echo in the city hall corridor, yet no one is there, and they stop if approached",
    "the merchant’s ledger reveals frequent sales to ‘N. Shade,’ who no one has seen in person",
    "someone found a hidden vault containing dozens of identical portraits of the same unknown woman",
    "the fishmonger’s stall occasionally smells like roses instead of fish, baffling everyone",
    "a star-shaped birthmark appears on newborns this month, rumored to foretell a great event",
    "the orchard orchard-keeper claims their orchard is haunted by apple-faced spirits singing lullabies"
  ]
};


